BOARD_TAG = mega2560
ARDUINO_SKETCHBOOK = $(realpath ..)
USER_LIB_PATH = $(realpath ../libraries)
ARDUINO_LIBS = robair \
               Adafruit_NeoPixel \
               Eyes \
               Papierlogik \
               md49 \
               ros_lib \
               Adafruit_TiCoServo

include ./paths.mk.defaults
-include ./paths.mk
include ../makefiles/Arduino.mk
